export const Objects =
   [
  "Fraise",
  "Éclipse",
  "Lustre",
  "Ketchup",
  "Dentifrice",
  "Arc-en-ciel",
  "Lit superposé",
  "Jeu de société",
  "Ruche",
  "Citron",
  "Couronne",
  "Gaufres",
  "Bulle",
  "Sifflet",
  "Boule de neige",
  "Bouquet",
  "Casque d’écoute",
  "Feux d’artifice",
  "Igloo",
  "Grande roue",
  "Peau de banane",
  "Tondeuse à gazon",
  "Été",
  "Fouet",
  "Cupcake",
  "Sac de couchage",
  "Blessure",
  "Brouillard",
  "Croûte",
  "Batterie"
]
export const Lieux = [
  "Paris",
  "Plage",
  "Montagnes",
  "USA",
  "Hôpital",
  "Grenier",
  "Japon",
  "Bibliothèque",
  "Désert",
  "Mars",
  "Pise",
  "Corse",
  "Ferme",
  "Mexique",
  "Mont Blanc",
  "Las Vegas",
  "Gare ferroviaire",
  "Pôle Nord",
  "Disney World",
];
export const Animaux =  [
  "Girafe",
  "Koala",
  "Guêpe",
  "Scorpion",
  "Lion",
  "Salamandre",
  "Dauphin",
  "Grenouille",
  "Panda",
  "ornithorynque",
  "T-rex",
  "Suricate",
  "Aigle"
];
export const Personne =  [
  "Facteur",
  "Superman",
  "Cowboy",
  "Tesla",
  "Vampire",
  "Pirate",
  "Girl Scout",
  "Pikachu",
  "Pèlerin",
  "Cendrillon",
  "Boulanger",
  "Napoléon",
  "Shrek",
  "Yoshi",
  "Robin des Bois",
  "Lutin de Noël",
  "Bob l’éponge",
  "Bébé Yoda",
  "Justin Beiber",
  "Harry Potter",
  "Reine Eilzabeth"
];
export const Action = [
  "Sauter",
  "Roter",
  "Cuisiner",
  "Gratter",
  "Dormir",
  "Planter",
  "Acheter",
  "Attacher",
  "Ronfler",
  "Attraper",
  "Étudier",
  "Envoyer un SMS"
];

export const Hard =  [
  "Jeux olympiques",
  "Château de sable",
  "Recycler",
  "Trou noir",
  "Applaudissements",
  "Blizzard",
  "Coup de soleil",
  "Machine à remonter le temps",
  "Dentelle",
  "Lundi",
  "Atlantis",
  "Marais",
  "Canal de Panama",
  "Crème solaire",
  "Dictionnaire",
  "Vanille",
  "Siècle"
];
